baseURL = "https://mather.github.io"
languageCode = "ja-jp"
defaultContentLanguage = "ja"

theme = "github.com/lxndrblz/anatole"

summarylength = 10
enableEmoji = true
enableRobotsTXT = true

metaDataFormat = "yaml"

# Syntax highlighting
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true



# Google Analytics
# googleAnalytics = "UA-39290733-1"

[blackfriday]
  # hrefTargetBlank = true
  # noreferrerLinks = true
  # nofollowLinks = true

[module]
  # uncomment line below for temporary local development of module
  # replacements = "github.com/lxndrblz/anatole -> ../../anatole"
  [[module.imports]]
    path = "github.com/lxndrblz/anatole"
    disable = false

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[params]
  title = "Reveal My Ignorance"
  author = "Kuwahata Eisuke"
  description = "Blog and Profile for Eisuke"
  profilePicture = "images/friendly-bear.png"
  images = ["images/friendly-bear.png"]
  copyright = "2018-{{ YEAR }} Kuwahata Eisuke All rights reserved."
  reversepagetitle = true

  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"
  singleDateFormat = "2006-01-02"
  indexDateFormat = "2006-01-02"
  listDateFormat = "2006-01-02"

  # images = [""]
  googleFonts = ["M+PLUS+1p:wght@400;700"]
  customCss = ["css/text_style.css"]

  doNotLoadAnimations = true

  gtagId = "GTM-M3PT4KW"

  # Social Icons
  [[params.socialIcons]]
    icon = "fab fa-facebook"
    title = "Facebook"
    url = "https://facebook.com/ekuwahata"

  [[params.socialIcons]]
    icon = "fab fa-instagram"
    title = "Instagram"
    url = "https://instagram.com/mather"

  [[params.socialIcons]]
    icon = "fab fa-youtube"
    title = "YouTube"
    url = "https://www.youtube.com/user/mather314"

  [[params.socialIcons]]
    icon = "fab fa-github"
    title = "Github"
    url = "https://github.com/mather"

  # KaTeX setting
  [params.math]
    enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
    use = "katex"  # options: "katex", "mathjax". default is "katex".

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 20

  [[menu.main]]
    name = "Profile"
    url = "/pages/profile/"
    weight = 30
