baseURL = "https://mather.github.io"
title = "Reveal My Ignorance"
theme = "hugo-coder"
languageCode = "ja"
defaultContentLanguage = "ja"

hasCJKLanguage = true
enableEmoji = true
enableRobotsTXT = true

[pagination]
pagerSize = 10

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[params]
  author = "Kuwahata Eisuke"
  info = ["認定こども園 園長", "元ソフトウェアエンジニア"]
  description = "Blog and Profile for Eisuke Kuwahata"
  keywords = "blog,developer,personal"
  avatarURL = "images/friendly-bear.png"
  dateFormat = "2006-01-02"
  since = 2019
  colorScheme = "auto"
  customCSS = ["css/text_style.css"]

  [params.googleTagManager]
    id = "G-ZCQPRE4NBR"

[[params.social]]
name = "GitHub"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/mather"

[[params.social]]
name = "Instagram"
icon = "fa-brands fa-instagram fa-2x"
weight = 2
url = "https://instagram.com/mather"

[[params.social]]
name = "YouTube"
icon = "fa-brands fa-youtube fa-2x"
weight = 3
url = "https://www.youtube.com/@mather314"

[[params.social]]
name = "Facebook"
icon = "fa-brands fa-facebook fa-2x"
weight = 4
url = "https://facebook.com/ekuwahata"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[[menu.main]]
name = "Posts"
weight = 1
url = "posts/"

[[menu.main]]
name = "Tags"
weight = 2
url = "tags/"

[[menu.main]]
name = "Profile"
weight = 3
url = "pages/profile/"
