name: Check PR

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v1
      - uses: actions/cache@v3
        with:
          path: $TMPDIR/hugo_cache/
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.17.6"
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          # The Hugo version to download (if necessary) and use. Example: 0.58.2
          hugo-version: "latest"
          # Download (if necessary) and use Hugo extended version. Example: true
          extended: true
      - name: Build Hugo
        run: hugo -v --minify --cacheDir=$TMPDIR/hugo_cache/
