name: Check PR

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: /tmp/hugo_cache/
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "^1.20.2"
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"
          extended: true
      - name: Build Hugo
        run: hugo -v --minify
