name: CI

on: 
  push:
    branches: 
      - hugo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v1
    - name: Hugo setup
      uses: peaceiris/actions-hugo@v2.3.0
      with:
        # The Hugo version to download (if necessary) and use. Example: 0.58.2
        hugo-version: 0.60.1
        # Download (if necessary) and use Hugo extended version. Example: true
        extended: true
    - name: Build Hugo
      run: hugo -v
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v2.5.1
      env:
        ACTIONS_DEPLOY_KEY: aaa
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./public
